// tools/build-macros.js - Generates one self-contained ONLYOFFICE macro per button.
// Usage: node tools/build-macros.js
//
// Each macro contains every /src module plus a call to SimulatorMain(action).
// The simulator state lives in the sheet (see src/state.js), so the macros
// do not depend on sharing variables with each other.

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC_DIR = path.join(ROOT, "src");
const OUT_DIR = path.join(ROOT, "dist", "macros");

// Load order: every module only references the ones above it at load time.
const MODULES = ["utils", "isa", "ram", "bus", "cpu", "alu", "decoder", "logger", "ui", "state", "main"];

const BUTTONS = {
    "load-program": "LOAD",
    "load-demo": "LOAD_DEMO",
    "step": "STEP",
    "run": "RUN",
    "run-to-end": "RUN_TO_END",
    "pause": "PAUSE",
    "reset": "RESET"
};

function indent(text) {
    return text.split("\n").map(line => (line.length > 0 ? "    " + line : line)).join("\n");
}

const bundle = MODULES
    .map(name => fs.readFileSync(path.join(SRC_DIR, name + ".js"), "utf8").trimEnd())
    .join("\n\n");

const buildId = new Date().toISOString().slice(0, 19).replace("T", " ");

fs.mkdirSync(OUT_DIR, { recursive: true });

for (const [file, action] of Object.entries(BUTTONS)) {
    const macro =
        `// ${action} button macro - generated by tools/build-macros.js from /src\n` +
        `(function () {\n` +
        `    const MACRO_BUILD = "${buildId}";\n\n` +
        `${indent(bundle)}\n\n` +
        `    SimulatorMain("${action}");\n` +
        `})();\n`;
    fs.writeFileSync(path.join(OUT_DIR, file + ".js"), macro);
    console.log(`dist/macros/${file}.js -> SimulatorMain("${action}")`);
}
console.log(`build ${buildId}`);
